version: '3.4'

services:
  node10:
    image: node:10
    container_name: #@ imageName('nodejs')
    volumes:
      - ${root_volume}:${root_point}
    expose:
      - 8080
#@ if not isParellel():
#@ if/end current_env == 'dev':
    ports:
      - '9080:8080'
#@ if/end current_env == 'test':
    ports:
      - '8080:8080'
#@ end
    command: [ 'tail', '-f', '/dev/null' ]

