
version: '3.4'

services:
  ocr:
    image: hertzg/tesseract-server
    container_name: #@ imageName('ocr')
    expose:
      - 8884
#@ if/end current_env == 'dev':
    ports:
      - '8884:8884'
#@ if/end current_env == 'test':
    ports:
      - '8884:8884'
    networks:
      default:
        aliases:
          - ocr.tool.net

