version: '3.4'

services:
  openjdk11:
    image: openjdk:11-jdk
    container_name: #@ imageName('jdk11')
    user: #@ hostUser()
    volumes:
      - "${root_volume}:${root_point}"
      - 'gradle-user-home:/tmp/tmp-user/.gradle'
      - ${work_dir}:${work_point}
    environment:
      GRADLE_USER_HOME: /tmp/tmp-user/.gradle
    command: [ 'tail', '-f', '/dev/null' ]

