version: '3.4'

services:
  web-driver:
    image: josephyao/selenium-video-ffmpeg:v0.0.3
    container_name: #@ imageName('selenium-video')
    volumes:
      - ../../videos:/videos
#@ if not isParellel():
#@ if/end current_env == 'test':
    ports:
      - "9000:9000"
#@ end
    networks:
      default:
        aliases:
          - selenium-video.tool.net

