version: '3.4'

services:
  web-driver:
    image: selenium/standalone-chrome:4.0.0-beta-3-20210426
    container_name: web-driver.${current_env}.${PROJECT_NAME}
#@ if/end current_env == 'test':
    ports:
      - '4444:4444'
      - '7900:7900'
    volumes:
      - ${work_dir}:${work_point}
    networks:
      default:
        aliases:
          - web-driver.tool.net
