version: '3.4'

services:
  mysql8:
    image: mysql/mysql-server:8.0
    container_name: #@ imageName('mysql')
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    expose:
      - 3306
#@ if not isParellel():
#@ if/end current_env == 'dev':
    ports:
      - "33306:3306"
#@ if/end current_env == 'test':
    ports:
      - "23306:3306"
#@ end
    volumes:
      - "../../core/composes/mysql8/conf:/etc/mysql/conf.d"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - mysql.tool.net
